name: Delete old packages

on:
  push:
  

jobs:
  delete-packages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/delete-package-versions@v3
        with:
          package-name: 'foundation'
          min-versions-to-keep: 10
