name: "Issue or PR or Comment"

on:
  # Trigger the workflow on new issues
  issues:
    types: [opened]
  # Trigger the workflow on new pull requests
  pull_request:
    types: [opened]
  # Trigger the workflow on new issue comments    
  issue_comment:
    types: [created]

# Allows the workflow to create comments on issues and pull requests
permissions:
  issues: write
  pull-requests: write

jobs:
  # This job only runs for issues
  issue:
    name: Issue opened
    if: ${{ github.event_name == 'issues' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  
      - name: Summary
        uses: actions/github-script@v6
        with:
          script: |
            await core.summary
              .addHeading(github.event_name)
              .addCodeBlock(JSON.stringify(github.event), "json")
              .write()    
      # - name: Summary
      #   run: |
      #     echo "## ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
      #     echo "```json" >> $GITHUB_STEP_SUMMARY
      #     EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
      #     echo "<<$EOF" >> $GITHUB_STEP_SUMMARY
      #     echo '${{ toJson(github.event) }}' >> $GITHUB_STEP_SUMMARY
      #     echo "$EOF" >> $GITHUB_STEP_SUMMARY
      #     echo "```" >> $GITHUB_STEP_SUMMARY


  # This job only runs for issue comments
  issue_comment:
    name: Issue comment
    if: ${{ github.event_name == 'issue_comment' && !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  
      - name: Summary
        uses: actions/github-script@v6
        with:
          script: |
            await core.summary
              .addHeading(github.event_name)
              .addCodeBlock(JSON.stringify(github.event), "json")
              .write()  
  # This job only runs for pull requests  
  pull_request:
    name: PR opened
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  
      - name: Summary
        uses: actions/github-script@v6
        with:
          script: |
            await core.summary
              .addHeading(github.event_name)
              .addCodeBlock(JSON.stringify(github.event), "json")
              .write()  

  # This job only runs for pull request comments  
  pull_request_comment:
    name: PR comment
    if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  
      - name: Summary
        uses: actions/github-script@v6
        with:
          script: |
            await core.summary
              .addHeading(github.event_name)
              .addCodeBlock(JSON.stringify(github.event), "json")
              .write()  
