name: "Workflow Dispatch"

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull Request Number"
        required: true

jobs:
  pr-workflow-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Workflow
        run: |
          echo "Running Workflow for PR ${{ github.event.inputs.pr_number }}"
          echo "Run your workflow here"

      - name: Complete Workflow
        run: |
          echo "Workflow for PR ${{ github.event.inputs.pr_number }} completed"